# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read.xci
# IP: The module: 'fifo_ddr3_read' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_read'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_read'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_read'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read.xci
# IP: The module: 'fifo_ddr3_read' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_read'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_read'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/34998/FPGA_Study/FPGA/Image_Capture_1A/Image_capture/Image_capture.srcs/sources_1/ip/fifo_ddr3_read/fifo_ddr3_read_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_ddr3_read'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
